services:
  books_recommendation_agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books_recommendation_agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


    env_file:
      - .env
    volumes:
      - ./books_recommendation_agent:/app/books_recommendation_agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - books_recommendation_agent-network


networks:
  books_recommendation_agent-network:
    driver: bridge
